# Prometheus configuration for quantitative trading platform monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'trading-platform'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Trading API application metrics
  - job_name: 'trading-api'
    static_configs:
      - targets: ['trading_api:8000']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Trading Dashboard metrics
  - job_name: 'trading-dashboard'
    static_configs:
      - targets: ['trading_dashboard:8501']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Data Collector metrics
  - job_name: 'data-collector'
    static_configs:
      - targets: ['data_collector:8002']
    metrics_path: /metrics
    scrape_interval: 30s

  # Backtesting Engine metrics
  - job_name: 'backtesting-engine'
    static_configs:
      - targets: ['backtesting_engine:8003']
    metrics_path: /metrics
    scrape_interval: 60s

  # Paper Trading metrics
  - job_name: 'paper-trading'
    static_configs:
      - targets: ['paper_trading:8004']
    metrics_path: /metrics
    scrape_interval: 30s

  # Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics

  # Custom trading metrics endpoint
  - job_name: 'trading-metrics'
    static_configs:
      - targets: ['trading_app:8005']
    metrics_path: /trading-metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    params:
      format: ['prometheus']

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Remote read configuration
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint/api/v1/read"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Storage configuration
storage:
  tsdb:
    path: /prometheus/
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true
