# config file version
apiVersion: 1

# list of datasources to insert/update
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
